version: '3.9'

services:

  crud-postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
    ports:
      - "5432:5432"
    networks:
      - crud-network

  sysmap-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - crud-postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://crud-postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    networks:
      - crud-network

networks:
  crud-network:
    driver: bridge
